# Generated by Django 4.0 on 2022-07-31 18:52

import app.models
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('submitter_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='fluency',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='corpus_name',
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to=functools.partial(app.models.file_path, *('audio',), **{})),
        ),
        migrations.AlterField(
            model_name='fluency',
            name='file',
            field=models.FileField(upload_to=functools.partial(app.models.file_path, *('fluency',), **{})),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Fail'), ('P', 'Processing')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='file',
            field=models.FileField(upload_to=functools.partial(app.models.file_path, *('transcript',), **{})),
        ),
        migrations.AddField(
            model_name='job',
            name='corpus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.corpus'),
        ),
    ]
