# Generated by Django 4.0 on 2022-07-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name_plural': 'Corpuses'},
        ),
        migrations.AlterModelOptions(
            name='fluency',
            options={'verbose_name_plural': 'Fluencies'},
        ),
    ]
