# Generated by Django 4.0 on 2022-07-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_corpus_rename_job_id_audio_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpus',
            old_name='submitter_email',
            new_name='maintainer_email',
        ),
    ]
